---
title: "CourseProject-GroupA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#A.  Business understanding

##A.1 	Business objectives
	1.  What is the market value of my house?
	2.  What improvements I can do to increase the value of my house? 
	3.  With a budget of $xxxx, where is the best location I can buy a house?
 
##A.2	Assessment
	The pertinent data will be gathered from different sources.
	1.  https://www.zoocasa.com - Available history of sold houses/condos  
	2.  https://open.toronto.ca/dataset/neighbourhoods/ - Toronto neighbourhood boundary data
	3.  https://torontolife.com/neighbourhood-rankings/ - Website that ranks Toronto neighbourhood in terms of Housing, Safety, Transit, etc.

	Technical Resources:
	1.  Oana Damian 
	2.  Junylou Daniel
	3.  Robin Mathew
	4.  Torsten Meyer

	Software Required:
	1.  R Library
	
	Hardware Required:
	1.  

	Assumption

	Constraints
	
	Terminology

	Cost and Benefits

##A.3	Mining Goals:
	1.  Predict house price given the location, type and features of the house.
	2.  Identify what features of the house mostly contribute to an increased value of the house
	3.  Identify which location has the best value given the type of house, features and neighbourhood. 

	The project will use clustering and linear prediction algorithm.  We expect an acceptable accuracy of 90%.


##A.4	Produce project plan


#B.  Data understanding
##B.1 Collect initial data
##B.2 Describe data
##B.3 Explore data
##B.4 Verify data quality

#C.  Data preparation
##C.1 Select data
##C.2 Clean data
##C.3 Construct data
##C.4 Integrate data
##C.5 Format data

#D.  Modeling
##D.1 Select modeling technique
##D.2 Generate test design
##D.3 Build model
##D.4 Assess model

#E.  Evaluation
##E.1 Evaluate results
##E.2 Review process
##E.3 Determine next steps

#F.  Deployment
##F.1 Plan deployment
##F.2 Plan monitoring and maintenance
##F.3 Produce final report
##F.4 Review project
